spring:
  datasource:
    url: jdbc:h2:mem:testdatabase
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
datasource:
  implementation: in-memory

